[package]
name = "common"
version = "0.1.0"
edition = "2018"
authors = ["pkornecki@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
sha1 = "0.6.0"
simple-error = "0.2.3"
